// Code generated by protoc-gen-go.
// source: apartment.proto
// DO NOT EDIT!

/*
Package apartment is a generated protocol buffer package.

It is generated from these files:
	apartment.proto

It has these top-level messages:
	Device
	GetDeviceRequest
	UpdateDeviceRequest
*/
package apartment

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Device struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	State bool   `protobuf:"varint,2,opt,name=state" json:"state,omitempty"`
}

func (m *Device) Reset()                    { *m = Device{} }
func (m *Device) String() string            { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()               {}
func (*Device) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetDeviceRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetDeviceRequest) Reset()                    { *m = GetDeviceRequest{} }
func (m *GetDeviceRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDeviceRequest) ProtoMessage()               {}
func (*GetDeviceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type UpdateDeviceRequest struct {
	Device *Device `protobuf:"bytes,1,opt,name=device" json:"device,omitempty"`
}

func (m *UpdateDeviceRequest) Reset()                    { *m = UpdateDeviceRequest{} }
func (m *UpdateDeviceRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateDeviceRequest) ProtoMessage()               {}
func (*UpdateDeviceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UpdateDeviceRequest) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

func init() {
	proto.RegisterType((*Device)(nil), "apartment.Device")
	proto.RegisterType((*GetDeviceRequest)(nil), "apartment.GetDeviceRequest")
	proto.RegisterType((*UpdateDeviceRequest)(nil), "apartment.UpdateDeviceRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Apartment service

type ApartmentClient interface {
	GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*Device, error)
	UpdateDevice(ctx context.Context, in *UpdateDeviceRequest, opts ...grpc.CallOption) (*Device, error)
}

type apartmentClient struct {
	cc *grpc.ClientConn
}

func NewApartmentClient(cc *grpc.ClientConn) ApartmentClient {
	return &apartmentClient{cc}
}

func (c *apartmentClient) GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*Device, error) {
	out := new(Device)
	err := grpc.Invoke(ctx, "/apartment.Apartment/GetDevice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apartmentClient) UpdateDevice(ctx context.Context, in *UpdateDeviceRequest, opts ...grpc.CallOption) (*Device, error) {
	out := new(Device)
	err := grpc.Invoke(ctx, "/apartment.Apartment/UpdateDevice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Apartment service

type ApartmentServer interface {
	GetDevice(context.Context, *GetDeviceRequest) (*Device, error)
	UpdateDevice(context.Context, *UpdateDeviceRequest) (*Device, error)
}

func RegisterApartmentServer(s *grpc.Server, srv ApartmentServer) {
	s.RegisterService(&_Apartment_serviceDesc, srv)
}

func _Apartment_GetDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApartmentServer).GetDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apartment.Apartment/GetDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApartmentServer).GetDevice(ctx, req.(*GetDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apartment_UpdateDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApartmentServer).UpdateDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apartment.Apartment/UpdateDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApartmentServer).UpdateDevice(ctx, req.(*UpdateDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Apartment_serviceDesc = grpc.ServiceDesc{
	ServiceName: "apartment.Apartment",
	HandlerType: (*ApartmentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDevice",
			Handler:    _Apartment_GetDevice_Handler,
		},
		{
			MethodName: "UpdateDevice",
			Handler:    _Apartment_UpdateDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("apartment.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x2c, 0x48, 0x2c,
	0x2a, 0xc9, 0x4d, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x28,
	0x19, 0x71, 0xb1, 0xb9, 0xa4, 0x96, 0x65, 0x26, 0xa7, 0x0a, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6,
	0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x22, 0x5c, 0xac, 0xc5, 0x25,
	0x89, 0x25, 0xa9, 0x12, 0x4c, 0x40, 0x41, 0x8e, 0x20, 0x08, 0x47, 0x49, 0x8d, 0x4b, 0xc0, 0x3d,
	0xb5, 0x04, 0xa2, 0x2d, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x04, 0x9b, 0x6e, 0x25, 0x07, 0x2e,
	0xe1, 0xd0, 0x82, 0x14, 0xa0, 0x0e, 0x54, 0xa5, 0x9a, 0x5c, 0x6c, 0x29, 0x60, 0x01, 0xb0, 0x62,
	0x6e, 0x23, 0x41, 0x3d, 0x84, 0xfb, 0xa0, 0x2a, 0xa1, 0x0a, 0x8c, 0xfa, 0x19, 0xb9, 0x38, 0x1d,
	0x61, 0x92, 0x42, 0xb6, 0x5c, 0x9c, 0x70, 0x7b, 0x85, 0xa4, 0x91, 0x74, 0xa1, 0xbb, 0x46, 0x0a,
	0xd3, 0x48, 0x25, 0x06, 0x21, 0x67, 0x2e, 0x1e, 0x64, 0xe7, 0x08, 0xc9, 0x21, 0x29, 0xc2, 0xe2,
	0x4e, 0xac, 0x86, 0x24, 0xb1, 0x81, 0x43, 0xd0, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x7f, 0xaa,
	0x7a, 0xd1, 0x54, 0x01, 0x00, 0x00,
}
